version: '2'

# Call this dockerfile with 
# docker-compose -f docker-compose.yml -f docker-compose-unified-search.yml up
services:

    # Registry, used for unified search set to use same es as geonode
    registry:
        container_name: registry
        image: registry
        build: ./docker/registry
        links:
            - search
        ports:
            - "8001"
        volumes:
            - scratch:/scratch

            # For local dev'ing, uncomment the below
            #  If using the line below verbatim, 
            #  registry must be cloned to ~/boundless/registry
            # - ~/boundless/registry:/opt/registry:ro

        networks:
            internal:
            # Expose on a fixed host IP for diagnostic purposes.
            external:
                ipv4_address: 172.16.238.6
        environment:
            # Setup registry to use included search
            - REGISTRY_SEARCH_URL=http://search:9200
  
    # Django app which presents an interface and ties everything else together
    exchange:
        environment:
            - ES_URL=http://search:9200
            - ES_UNIFIED_SEARCH=True
            - REGISTRYURL=http://172.16.238.6:8001
            - REGISTRY_LOCAL_URL=http://172.16.238.6:8001
